export interface CountryCode {
  readonly code: string;
  readonly countryAr: string;
  readonly countryEn: string;
  readonly flag: string;
  readonly iso: string;
}

export const ALL_COUNTRY_CODES: readonly CountryCode[] = [
  // ── Arab & GCC Countries (Top Priority) ──
  { code: "+966", countryAr: "السعودية", countryEn: "Saudi Arabia", flag: "🇸🇦", iso: "SA" },
  { code: "+971", countryAr: "الإمارات العربية المتحدة", countryEn: "UAE", flag: "🇦🇪", iso: "AE" },
  { code: "+965", countryAr: "الكويت", countryEn: "Kuwait", flag: "🇰🇼", iso: "KW" },
  { code: "+974", countryAr: "قطر", countryEn: "Qatar", flag: "🇶🇦", iso: "QA" },
  { code: "+968", countryAr: "عُمان", countryEn: "Oman", flag: "🇴🇲", iso: "OM" },
  { code: "+973", countryAr: "البحرين", countryEn: "Bahrain", flag: "🇧🇭", iso: "BH" },
  { code: "+20", countryAr: "مصر", countryEn: "Egypt", flag: "🇪🇬", iso: "EG" },
  { code: "+962", countryAr: "الأردن", countryEn: "Jordan", flag: "🇯🇴", iso: "JO" },
  { code: "+970", countryAr: "فلسطين", countryEn: "Palestine", flag: "🇵🇸", iso: "PS" },
  { code: "+964", countryAr: "العراق", countryEn: "Iraq", flag: "🇮🇶", iso: "IQ" },
  { code: "+213", countryAr: "الجزائر", countryEn: "Algeria", flag: "🇩🇿", iso: "DZ" },
  { code: "+212", countryAr: "المغرب", countryEn: "Morocco", flag: "🇲🇦", iso: "MA" },
  { code: "+216", countryAr: "تونس", countryEn: "Tunisia", flag: "🇹🇳", iso: "TN" },
  { code: "+218", countryAr: "ليبيا", countryEn: "Libya", flag: "🇱🇾", iso: "LY" },
  { code: "+249", countryAr: "السودان", countryEn: "Sudan", flag: "🇸🇩", iso: "SD" },
  { code: "+967", countryAr: "اليمن", countryEn: "Yemen", flag: "🇾🇪", iso: "YE" },
  { code: "+963", countryAr: "سوريا", countryEn: "Syria", flag: "🇸🇾", iso: "SY" },
  { code: "+961", countryAr: "لبنان", countryEn: "Lebanon", flag: "🇱🇧", iso: "LB" },
  { code: "+222", countryAr: "موريتانيا", countryEn: "Mauritania", flag: "🇲🇷", iso: "MR" },
  { code: "+252", countryAr: "الصومال", countryEn: "Somalia", flag: "🇸🇴", iso: "SO" },
  { code: "+253", countryAr: "جيبوتي", countryEn: "Djibouti", flag: "🇩🇯", iso: "DJ" },
  { code: "+269", countryAr: "جزر القمر", countryEn: "Comoros", flag: "🇰🇲", iso: "KM" },

  // ── Americas ──
  { code: "+1", countryAr: "الولايات المتحدة", countryEn: "United States", flag: "🇺🇸", iso: "US" },
  { code: "+1", countryAr: "كندا", countryEn: "Canada", flag: "🇨🇦", iso: "CA" },
  { code: "+52", countryAr: "المكسيك", countryEn: "Mexico", flag: "🇲🇽", iso: "MX" },
  { code: "+55", countryAr: "البرازيل", countryEn: "Brazil", flag: "🇧🇷", iso: "BR" },
  { code: "+54", countryAr: "الأرجنتين", countryEn: "Argentina", flag: "🇦🇷", iso: "AR" },
  { code: "+56", countryAr: "تشيلي", countryEn: "Chile", flag: "🇨🇱", iso: "CL" },
  { code: "+57", countryAr: "كولومبيا", countryEn: "Colombia", flag: "🇨🇴", iso: "CO" },
  { code: "+51", countryAr: "بيرو", countryEn: "Peru", flag: "🇵🇪", iso: "PE" },
  { code: "+58", countryAr: "فنزويلا", countryEn: "Venezuela", flag: "🇻🇪", iso: "VE" },
  { code: "+593", countryAr: "الإكوادور", countryEn: "Ecuador", flag: "🇪🇨", iso: "EC" },
  { code: "+595", countryAr: "باراغواي", countryEn: "Paraguay", flag: "🇵🇾", iso: "PY" },
  { code: "+598", countryAr: "أوروغواي", countryEn: "Uruguay", flag: "🇺🇾", iso: "UY" },
  { code: "+591", countryAr: "بوليفيا", countryEn: "Bolivia", flag: "🇧🇴", iso: "BO" },
  { code: "+506", countryAr: "كوستاريكا", countryEn: "Costa Rica", flag: "🇨🇷", iso: "CR" },
  { code: "+507", countryAr: "بنما", countryEn: "Panama", flag: "🇵🇦", iso: "PA" },
  { code: "+503", countryAr: "السلفادور", countryEn: "El Salvador", flag: "🇸🇻", iso: "SV" },
  { code: "+504", countryAr: "هندوراس", countryEn: "Honduras", flag: "🇭🇳", iso: "HN" },
  { code: "+505", countryAr: "نيكاراغوا", countryEn: "Nicaragua", flag: "🇳🇮", iso: "NI" },
  { code: "+502", countryAr: "غواتيمالا", countryEn: "Guatemala", flag: "🇬🇹", iso: "GT" },
  { code: "+53", countryAr: "كوبا", countryEn: "Cuba", flag: "🇨🇺", iso: "CU" },
  { code: "+509", countryAr: "هايتي", countryEn: "Haiti", flag: "🇭🇹", iso: "HT" },
  { code: "+1809", countryAr: "جمهورية الدومينيكان", countryEn: "Dominican Republic", flag: "🇩🇴", iso: "DO" },
  { code: "+1876", countryAr: "جاماييكا", countryEn: "Jamaica", flag: "🇯🇲", iso: "JM" },

  // ── Europe ──
  { code: "+44", countryAr: "المملكة المتحدة", countryEn: "United Kingdom", flag: "🇬🇧", iso: "GB" },
  { code: "+33", countryAr: "فرنسا", countryEn: "France", flag: "🇫🇷", iso: "FR" },
  { code: "+49", countryAr: "ألمانيا", countryEn: "Germany", flag: "🇩🇪", iso: "DE" },
  { code: "+39", countryAr: "إيطاليا", countryEn: "Italy", flag: "🇮🇹", iso: "IT" },
  { code: "+34", countryAr: "إسبانيا", countryEn: "Spain", flag: "🇪🇸", iso: "ES" },
  { code: "+31", countryAr: "هولندا", countryEn: "Netherlands", flag: "🇳🇱", iso: "NL" },
  { code: "+32", countryAr: "بلجيكا", countryEn: "Belgium", flag: "🇧🇪", iso: "BE" },
  { code: "+41", countryAr: "سويسرا", countryEn: "Switzerland", flag: "🇨🇭", iso: "CH" },
  { code: "+43", countryAr: "النمسا", countryEn: "Austria", flag: "🇦🇹", iso: "AT" },
  { code: "+46", countryAr: "السويد", countryEn: "Sweden", flag: "🇸🇪", iso: "SE" },
  { code: "+47", countryAr: "النرويج", countryEn: "Norway", flag: "🇳🇴", iso: "NO" },
  { code: "+45", countryAr: "الدنمارك", countryEn: "Denmark", flag: "🇩🇰", iso: "DK" },
  { code: "+358", countryAr: "فنلندا", countryEn: "Finland", flag: "🇫🇮", iso: "FI" },
  { code: "+351", countryAr: "البرتغال", countryEn: "Portugal", flag: "🇵🇹", iso: "PT" },
  { code: "+353", countryAr: "أيرلندا", countryEn: "Ireland", flag: "🇮🇪", iso: "IE" },
  { code: "+48", countryAr: "بولندا", countryEn: "Poland", flag: "🇵🇱", iso: "PL" },
  { code: "+36", countryAr: "المجر", countryEn: "Hungary", flag: "🇭🇺", iso: "HU" },
  { code: "+420", countryAr: "التشيك", countryEn: "Czech Republic", flag: "🇨🇿", iso: "CZ" },
  { code: "+421", countryAr: "سلوفاكيا", countryEn: "Slovakia", flag: "🇸🇰", iso: "SK" },
  { code: "+30", countryAr: "اليونان", countryEn: "Greece", flag: "🇬🇷", iso: "GR" },
  { code: "+90", countryAr: "تركيا", countryEn: "Turkey", flag: "🇹🇷", iso: "TR" },
  { code: "+380", countryAr: "أوكرانيا", countryEn: "Ukraine", flag: "🇺🇦", iso: "UA" },
  { code: "+40", countryAr: "رومانيا", countryEn: "Romania", flag: "🇷🇴", iso: "RO" },
  { code: "+359", countryAr: "بلغاريا", countryEn: "Bulgaria", flag: "🇧🇬", iso: "BG" },
  { code: "+385", countryAr: "كرواتيا", countryEn: "Croatia", flag: "🇭🇷", iso: "HR" },
  { code: "+386", countryAr: "سلوفينيا", countryEn: "Slovenia", flag: "🇸🇮", iso: "SI" },
  { code: "+381", countryAr: "صربيا", countryEn: "Serbia", flag: "🇷🇸", iso: "RS" },
  { code: "+387", countryAr: "البوسنة والهرسك", countryEn: "Bosnia & Herzegovina", flag: "🇧🇦", iso: "BA" },
  { code: "+355", countryAr: "ألبانيا", countryEn: "Albania", flag: "🇦🇱", iso: "AL" },
  { code: "+389", countryAr: "مقدونيا الشمالية", countryEn: "North Macedonia", flag: "🇲🇰", iso: "MK" },
  { code: "+373", countryAr: "مولدوفا", countryEn: "Moldova", flag: "🇲🇩", iso: "MD" },
  { code: "+375", countryAr: "بيلاروسيا", countryEn: "Belarus", flag: "🇧🇾", iso: "BY" },
  { code: "+370", countryAr: "ليتوانيا", countryEn: "Lithuania", flag: "🇱🇹", iso: "LT" },
  { code: "+371", countryAr: "لاتفيا", countryEn: "Latvia", flag: "🇱🇻", iso: "LV" },
  { code: "+372", countryAr: "إستونيا", countryEn: "Estonia", flag: "🇪🇪", iso: "EE" },
  { code: "+356", countryAr: "مالطا", countryEn: "Malta", flag: "🇲🇹", iso: "MT" },
  { code: "+357", countryAr: "قبرص", countryEn: "Cyprus", flag: "🇨🇾", iso: "CY" },
  { code: "+352", countryAr: "لوكسمبورغ", countryEn: "Luxembourg", flag: "🇱🇺", iso: "LU" },
  { code: "+354", countryAr: "آيسلندا", countryEn: "Iceland", flag: "🇮🇸", iso: "IS" },
  { code: "+376", countryAr: "أندورا", countryEn: "Andorra", flag: "🇦🇩", iso: "AD" },
  { code: "+377", countryAr: "موناكو", countryEn: "Monaco", flag: "🇲🇨", iso: "MC" },
  { code: "+378", countryAr: "سان مارينو", countryEn: "San Marino", flag: "🇸🇲", iso: "SM" },

  // ── Asia & Pacific ──
  { code: "+86", countryAr: "الصين", countryEn: "China", flag: "🇨🇳", iso: "CN" },
  { code: "+81", countryAr: "اليابان", countryEn: "Japan", flag: "🇯🇵", iso: "JP" },
  { code: "+82", countryAr: "كوريا الجنوبية", countryEn: "South Korea", flag: "🇰🇷", iso: "KR" },
  { code: "+91", countryAr: "الهند", countryEn: "India", flag: "🇮🇳", iso: "IN" },
  { code: "+92", countryAr: "باكستان", countryEn: "Pakistan", flag: "🇵🇰", iso: "PK" },
  { code: "+880", countryAr: "بنغلاديش", countryEn: "Bangladesh", flag: "🇧🇩", iso: "BD" },
  { code: "+60", countryAr: "ماليزيا", countryEn: "Malaysia", flag: "🇲🇾", iso: "MY" },
  { code: "+62", countryAr: "إندونيسيا", countryEn: "Indonesia", flag: "🇮🇩", iso: "ID" },
  { code: "+63", countryAr: "الفلبين", countryEn: "Philippines", flag: "🇵🇭", iso: "PH" },
  { code: "+66", countryAr: "تايلاند", countryEn: "Thailand", flag: "🇹🇭", iso: "TH" },
  { code: "+84", countryAr: "فيتنام", countryEn: "Vietnam", flag: "🇻🇳", iso: "VN" },
  { code: "+65", countryAr: "سنغافورة", countryEn: "Singapore", flag: "🇸🇬", iso: "SG" },
  { code: "+852", countryAr: "هونغ كونغ", countryEn: "Hong Kong", flag: "🇭🇰", iso: "HK" },
  { code: "+886", countryAr: "تايوان", countryEn: "Taiwan", flag: "🇹🇼", iso: "TW" },
  { code: "+61", countryAr: "أستراليا", countryEn: "Australia", flag: "🇦🇺", iso: "AU" },
  { code: "+64", countryAr: "نيوزيلندا", countryEn: "New Zealand", flag: "🇳🇿", iso: "NZ" },
  { code: "+94", countryAr: "سريلانكا", countryEn: "Sri Lanka", flag: "🇱🇰", iso: "LK" },
  { code: "+977", countryAr: "نيبال", countryEn: "Nepal", flag: "🇳🇵", iso: "NP" },
  { code: "+95", countryAr: "ميانمار", countryEn: "Myanmar", flag: "🇲🇲", iso: "MM" },
  { code: "+855", countryAr: "كمبوديا", countryEn: "Cambodia", flag: "🇰🇭", iso: "KH" },
  { code: "+856", countryAr: "لاوس", countryEn: "Laos", flag: "🇱🇦", iso: "LA" },
  { code: "+673", countryAr: "بروناي", countryEn: "Brunei", flag: "🇧🇳", iso: "BN" },
  { code: "+960", countryAr: "جزر المالديف", countryEn: "Maldives", flag: "🇲🇻", iso: "MV" },
  { code: "+975", countryAr: "بوتان", countryEn: "Bhutan", flag: "🇧🇹", iso: "BT" },
  { code: "+98", countryAr: "إيران", countryEn: "Iran", flag: "🇮🇷", iso: "IR" },
  { code: "+93", countryAr: "أفغانستان", countryEn: "Afghanistan", flag: "🇦🇫", iso: "AF" },
  { code: "+7", countryAr: "روسيا / كازاخستان", countryEn: "Russia / Kazakhstan", flag: "🇷🇺", iso: "RU" },
  { code: "+998", countryAr: "أوزبكستان", countryEn: "Uzbekistan", flag: "🇺🇿", iso: "UZ" },
  { code: "+994", countryAr: "أذربيجان", countryEn: "Azerbaijan", flag: "🇦🇿", iso: "AZ" },
  { code: "+995", countryAr: "جورجيا", countryEn: "Georgia", flag: "🇬🇪", iso: "GE" },
  { code: "+374", countryAr: "أرمينيا", countryEn: "Armenia", flag: "🇦🇲", iso: "AM" },
  { code: "+996", countryAr: "قيرغيزستان", countryEn: "Kyrgyzstan", flag: "🇰🇬", iso: "KG" },
  { code: "+992", countryAr: "طاجيكستان", countryEn: "Tajikistan", flag: "🇹🇯", iso: "TJ" },
  { code: "+993", countryAr: "تركمانستان", countryEn: "Turkmenistan", flag: "🇹🇲", iso: "TM" },
  { code: "+976", countryAr: "منغوليا", countryEn: "Mongolia", flag: "🇲🇳", iso: "MN" },

  // ── Africa ──
  { code: "+27", countryAr: "جنوب أفريقيا", countryEn: "South Africa", flag: "🇿🇦", iso: "ZA" },
  { code: "+234", countryAr: "نيجيريا", countryEn: "Nigeria", flag: "🇳🇬", iso: "NG" },
  { code: "+254", countryAr: "كينيا", countryEn: "Kenya", flag: "🇰🇪", iso: "KE" },
  { code: "+251", countryAr: "إثيوبيا", countryEn: "Ethiopia", flag: "🇪🇹", iso: "ET" },
  { code: "+233", countryAr: "غانا", countryEn: "Ghana", flag: "🇬🇭", iso: "GH" },
  { code: "+225", countryAr: "ساحل العاج", countryEn: "Ivory Coast", flag: "🇨🇮", iso: "CI" },
  { code: "+221", countryAr: "السنغال", countryEn: "Senegal", flag: "🇸🇳", iso: "SN" },
  { code: "+255", countryAr: "تنزانيا", countryEn: "Tanzania", flag: "🇹🇿", iso: "TZ" },
  { code: "+256", countryAr: "أوغندا", countryEn: "Uganda", flag: "🇺🇬", iso: "UG" },
  { code: "+250", countryAr: "رواندا", countryEn: "Rwanda", flag: "🇷🇼", iso: "RW" },
  { code: "+237", countryAr: "الكاميرون", countryEn: "Cameroon", flag: "🇨🇲", iso: "CM" },
  { code: "+260", countryAr: "زامبيا", countryEn: "Zambia", flag: "🇿🇲", iso: "ZM" },
  { code: "+263", countryAr: "زيمبابوي", countryEn: "Zimbabwe", flag: "🇿🇼", iso: "ZW" },
  { code: "+264", countryAr: "ناميبيا", countryEn: "Namibia", flag: "🇳🇦", iso: "NA" },
  { code: "+267", countryAr: "بوتسوانا", countryEn: "Botswana", flag: "🇧🇼", iso: "BW" },
  { code: "+230", countryAr: "موريشيوس", countryEn: "Mauritius", flag: "🇲🇺", iso: "MU" },
  { code: "+261", countryAr: "مدغشقر", countryEn: "Madagascar", flag: "🇲🇬", iso: "MG" },
  { code: "+244", countryAr: "أنغولا", countryEn: "Angola", flag: "🇦🇴", iso: "AO" },
  { code: "+258", countryAr: "موزمبيق", countryEn: "Mozambique", flag: "🇲🇿", iso: "MZ" },
] as const;
